### ISSUE TITLE
v-alpha-0.0.0

### ISSUE THREAD

**Issue by Deep-Codes** [Deep-Codes/chloromaps#5]
Issue Tracker for v-alpha-0.0.0 release 1st June.

## 🚀 Priority

- [x] #4 Adds a new Control Container for Horizontal and Vertical Map Variant
- [x] #4 Adding a Sticky Navbar and some dumb navlinks
- [x] #4 Change Default Map Bg
- [x] #4 Disable fill transition for Map Editors
- [x] #6 Labels Store and Operations
- [x] #7  Use Vanilla API instead of React ones to avoid Massive State / Renders
- [x] #8  Labels in  Config
- [x] 7fb02c62bf6c551acd820d264ebe43a6d32e4414 Scroll to Center on Smaller Viewports
- [x] fedb4c1e5f68318a33d8912609ae296480543e02 Option to Disable Tooltip
- [x] 0ea9706ea88baaec91253189dec8f051e5784f0e Insert Data for Caucasian Region
- [x] e9fc0d5 Fix the varies font size of labels in different maps (`scallingFactor`)
- [x] #9 Labels Stuff
   - [x] f079399 Controls for Label Font-Size
   - [x] 44fa01f Controls for Label Colors
   - [x] dd132c4 & 1d6fd6d Resolve Label Props in Configs
   - [x] 5e820d3  Switch Label Container to Table
- [x] `toFixed` in all coords values
- [x] 9e0085c Controls for Legend Color
- [x] #10  Fix Widths of Control Boxes
- [x] 89da518 Fix Reset for Labels 
- [x] 2b27b06 Features Cards
- [x] 30a4a99 Add Icons to Features
- [x] 3b82735 Merge Legend + Label Tab
- [x] 4045c02 Default Map , Border Color doesn't Reset
- [ ] Fix Upload File Button Click Area
- [ ] Merge Map and Legend in 1 SVG instead of 2  (Possilbe with Changing 4th param of `viewBox`)
- [ ] Tooltip Styles
- [x] f6787cc  `/map` route with all maps + `More Maps` Button 
- [x] f320943 Search Input for Finding Maps
- [x] 2a35851 Script to Automate Building / Adding Template
- [ ] `Tags` for Map Projections

## 😇 Not that Important, but Good if done

- [ ] SVG Patterns
- [ ] Resolve StateCodes from Saved Config
- [ ] Able to Change DownloadMapBg
- [ ] Integrate Real-Time Covid Heat Maps

## 😅 Not Important At all just Touch-ups

- [ ] Source Annotaion in Legend SVG
- [ ] Landing Cards
- [ ] Landing Features
- [ ] LightHouse Near Perfect (`perf`)
- [ ] Div Button Clicks on Keyboard
- [ ] SEO for Every Page
- [ ] OG:image for Each Variants
- [ ] Add Examples for All
- [ ] Changes not Saved Modal
- [ ] Footer Component
- [ ] Add Road Map / Changelog
- [ ] Share on Social Cards
